name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'  # Adjust the Perl version if needed


      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libltdl-dev libnsl-dev

          # - name: Install PAR::Packer
          #   run: cpanm --notest PAR::Packer

      - name: Install PAR::Packer with verbose logging
        run: cpanm --notest --verbose PAR::Packer 2>&1 | tee cpanm.log
      - name: Upload cpanm log
        uses: actions/upload-artifact@v4
        with:
          name: cpanm-log
          path: cpanm.log

      - name: Compile Perl Script to Binary
        run: pp -M Tie::IxHash -o sbatch-script-generator sbatchGenerator.pl

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: perl-binary-${{ runner.os }}
          path: sbatch-script-generator

